### PR TITLE
Kh.add topos zkevm demo

### PR DESCRIPTION
**Pull request by wyhaines**
# Description

Here is the documentation/walkthrough for the topos-zkevm-demo CLI. It is based very closely on Seb's WALKTHROUGH.md that he originally did for the topos-zkevm-demo repository. I've made a few wording changes in a few places, either to fix small errors, or to rephrase in a way that felt like it flowed better. I have also included animated GIFs for most of the sections that show what it looks like to run each section.

A quick note about the GIF files.  Gatsby automatically preprocesses images, creating several scaled versions so that the pages more readily, and transparently adapt to different screen sizes. The mechanism that it uses to do this does not work for GIF files, which means that Gatsby doesn't show images of that type much love. There are some plugins for Gatsby that can help, but there be potential dragons there, as I discovered when trying to make that approach work for the EEAP site. The solution that I settled on there, as the one that caused the least pain, was to have a `Gif` widget that renders the gifs. It's an implemented, working solution on that site, so I used it here, as well, and it works pretty well for the kind of GIF use that we typically have.

## PR Checklist:

- [ X ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

### CODE REVIEW

**Comment by sebastiendan** [comment]
@wyhaines If I'm not wrong, the Gatsby thing with images is optional and is only used if you want it. I think you can simply use an `` tag with an image from the `static` folder and it should work. For instance, in toposware.com, I used the Gatsby image plugin for things like blog articles thumbnails and headers, but not most UI elements like icons, boxes, etc.

**Comment by sebastiendan** [comment]
One only comment: gifs are rendered way too small, it's almost impossible to read what's happening (on my mac 13" screen)

**Review by sebastiendan — CHANGES_REQUESTED** [review]
One only comment: gifs are rendered way too small, it's almost impossible to read what's happening (on my mac 13" screen)

**Comment by wyhaines** [comment]
> One only comment: gifs are rendered way too small, it's almost impossible to read what's happening (on my mac 13" screen)

Fair. I scaled them to 60%, but I'm on a big monitor.  I'll revise.

**Comment by wyhaines** [comment]
> @wyhaines If I'm not wrong, the Gatsby thing with images is optional and is only used if you want it. I think you can simply use an `` tag with an image from the `static` folder and it should work. For instance, in toposware.com, I used the Gatsby image plugin for things like blog articles thumbnails and headers, but not most UI elements like icons, boxes, etc.

You're not wrong. Thank you for pointing it out. I've yanked that component from the codebase.  :)

**Comment by wyhaines** [comment]
> One only comment: gifs are rendered way too small, it's almost impossible to read what's happening (on my mac 13" screen)

I removed all of the scaling.

**Review by sebastiendan — APPROVED** [review]

**Pull request merged**
